require "digest/md5"
require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
    put "Executando uma tarefa de teste"
end

task :local_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
    users = [
        { name: "Tiago Dias", email: "tf.dias@gmail.com", password: to_md5("pwd123") },
        { name: "Tiago Felipe", email: "tf.dias.oliveira@gmail.com", password: to_md5("pwd123") },
        { name: "Skisperd", email: "skisperd@gmail.com", password: to_md5("pwd123") },
      ]
  
      MongoDB.new.drop_danger
      MongoDB.new.insert_users(users)

      #sh "cucumber"
end